# Main application 
configservice:
  replicaCount: 2
  image:
    repository: docker.io/library/config-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  # Names of Kubernetes secrets to which configservice will have access
  secrets:
  - config-service-mongodb
  - config-service-redis

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}

  probes:
    livenessProbe:
      initialDelaySeconds: 15
    readinessProbe:
      initialDelaySeconds: 15

  service:
    type: LoadBalancer
    port: 5055
    tagetPort: 5000

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podSecurityContext:
    fsGroup: 1001
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsGroup: 0
    runAsNonRoot: true
    runAsUser: 1001

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Database
mongodb:
  enabled: true
  architecture: standalone
  updateStrategy:
    type: Recreate
  image:
    tag: 7.0.0-jammy
    repository: arm64v8/mongo
  persistence:
    mountPath: /data/db
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Cache 
redis:
  enabled: true
  master:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 100Mi
  replica:
    replicaCount: 3
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 100Mi
