apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-service.fullname" . }}
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.configservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "config-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "config-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "config-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.configservice.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.configservice.securityContext | nindent 12 }}
        image: "{{ .Values.configservice.image.repository }}:{{ .Values.configservice.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.configservice.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.configservice.service.tagetPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          {{- toYaml .Values.configservice.resources | nindent 12 }}
