kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: config-service
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  resourceNames:
  - config-service-mongodb
  - config-service-redis
  verbs: ["get", "watch", "list"]