kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "config-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "config-service.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "config-service.fullname" . }}
  apiGroup: ""
