kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "config-service.fullname" . }}
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  resourceNames:
    {{ toYaml .Values.configservice.secrets | nindent 2 }}
  verbs: ["get", "watch", "list"]