apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  type: {{ .Values.configservice.service.type }}
  ports:
    - port: {{ .Values.configservice.service.port }}
      targetPort: {{ .Values.configservice.service.tagetPort }}
      protocol: TCP
      name: http
  selector:
    app: config-service
