apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-service.fullname" . }}
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.configservice.service.type }}
  ports:
    - port: {{ .Values.configservice.service.port }}
      targetPort: {{ .Values.configservice.service.tagetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "config-service.selectorLabels" . | nindent 4 }}
